version: 2
jobs:
  build:
    docker:
      - image: cotoami/cotoami-elixir:1.6
      - image: circleci/postgres:9.5-alpine
      - image: redis:alpine
      - image: neo4j:3.2.2
        environment:
        - NEO4J_AUTH=none
    working_directory: ~/cotoami
    steps:
      - checkout
      - run:
          name: Compile app
          command: mix do deps.get, deps.compile, compile
          environment:
            MIX_ENV: prod
      - run:
          name: Install node modules
          command: cd assets && npm install --unsafe-perm
          # ref. https://github.com/npm/npm/issues/3497
      - run:
          name: Check elm sources are formatted
          command: cd assets && npm run elm-format:validate
      - run:
          name: Fix elm-make
          command: ./.circleci/fix-elm-make.sh
      - run:
          name: Compile assets
          command: cd assets && npm run deploy && npm run deploy
          # ref. https://github.com/madsflensted/elm-brunch/issues/26
      - run:
          name: Digest and compress static files
          command: mix phx.digest
      - run:
          name: Install dockerize
          command: ./.circleci/install-dockerize.sh
      - run:
          name: Wait for postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for neo4j to be ready
          command: dockerize -wait tcp://localhost:7687 -timeout 1m
      - run:
          name: Test app
          command: mix do compile, test
          environment:
            MIX_ENV: test
      - save_cache:
          key: work-dir-{{ .Revision }}
          paths:
            - ~/cotoami

  release-develop:
    docker:
      - image: docker:17.06
    working_directory: ~/cotoami
    steps:
      - setup_remote_docker
      - restore_cache:
          keys:
            - work-dir-{{ .Revision }}
      - run:
          name: Build docker image
          command: docker build -t cotoami/cotoami:develop .
      - run:
          name: Release docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push cotoami/cotoami:develop

  deploy-develop:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: ./.circleci/install-kubectl.sh
      - deploy:
          command: ./.circleci/deploy-develop.sh

  release:
    docker:
      - image: docker:17.06
    working_directory: ~/cotoami
    steps:
      - setup_remote_docker
      - restore_cache:
          keys:
            - work-dir-{{ .Revision }}
      - run:
          name: Build docker image
          command: docker build -t cotoami/cotoami:$CIRCLE_TAG .
      - run:
          name: Release docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push cotoami/cotoami:$CIRCLE_TAG
            docker tag cotoami/cotoami:$CIRCLE_TAG cotoami/cotoami:latest
            docker push cotoami/cotoami:latest

  deploy:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: ./.circleci/install-kubectl.sh
      - deploy:
          command: |
            ~/.kube/kubectl config use-context $KUBE_CONTEXT
            ~/.kube/kubectl --namespace='prod-cotoami' set image deployment/cotoami cotoami=cotoami/cotoami:$CIRCLE_TAG

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release-develop:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy-develop:
          requires:
            - release-develop
          filters:
            branches:
              only: develop
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - release
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
